-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE IF NOT EXISTS "pg_stat_statements_info" (
	"dealloc" bigint,
	"stats_reset" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pg_stat_statements" (
	"userid" "oid",
	"dbid" "oid",
	"toplevel" boolean,
	"queryid" bigint,
	"query" text,
	"plans" bigint,
	"total_plan_time" double precision,
	"min_plan_time" double precision,
	"max_plan_time" double precision,
	"mean_plan_time" double precision,
	"stddev_plan_time" double precision,
	"calls" bigint,
	"total_exec_time" double precision,
	"min_exec_time" double precision,
	"max_exec_time" double precision,
	"mean_exec_time" double precision,
	"stddev_exec_time" double precision,
	"rows" bigint,
	"shared_blks_hit" bigint,
	"shared_blks_read" bigint,
	"shared_blks_dirtied" bigint,
	"shared_blks_written" bigint,
	"local_blks_hit" bigint,
	"local_blks_read" bigint,
	"local_blks_dirtied" bigint,
	"local_blks_written" bigint,
	"temp_blks_read" bigint,
	"temp_blks_written" bigint,
	"blk_read_time" double precision,
	"blk_write_time" double precision,
	"wal_records" bigint,
	"wal_fpi" bigint,
	"wal_bytes" numeric
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pg_stat_kcache_detail" (
	"query" text,
	"top" boolean,
	"datname" "name",
	"rolname" "name",
	"plan_user_time" double precision,
	"plan_system_time" double precision,
	"plan_minflts" bigint,
	"plan_majflts" bigint,
	"plan_nswaps" bigint,
	"plan_reads" bigint,
	"plan_reads_blks" bigint,
	"plan_writes" bigint,
	"plan_writes_blks" bigint,
	"plan_msgsnds" bigint,
	"plan_msgrcvs" bigint,
	"plan_nsignals" bigint,
	"plan_nvcsws" bigint,
	"plan_nivcsws" bigint,
	"exec_user_time" double precision,
	"exec_system_time" double precision,
	"exec_minflts" bigint,
	"exec_majflts" bigint,
	"exec_nswaps" bigint,
	"exec_reads" bigint,
	"exec_reads_blks" bigint,
	"exec_writes" bigint,
	"exec_writes_blks" bigint,
	"exec_msgsnds" bigint,
	"exec_msgrcvs" bigint,
	"exec_nsignals" bigint,
	"exec_nvcsws" bigint,
	"exec_nivcsws" bigint
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pg_stat_kcache" (
	"datname" "name",
	"plan_user_time" double precision,
	"plan_system_time" double precision,
	"plan_minflts" numeric,
	"plan_majflts" numeric,
	"plan_nswaps" numeric,
	"plan_reads" numeric,
	"plan_reads_blks" numeric,
	"plan_writes" numeric,
	"plan_writes_blks" numeric,
	"plan_msgsnds" numeric,
	"plan_msgrcvs" numeric,
	"plan_nsignals" numeric,
	"plan_nvcsws" numeric,
	"plan_nivcsws" numeric,
	"exec_user_time" double precision,
	"exec_system_time" double precision,
	"exec_minflts" numeric,
	"exec_majflts" numeric,
	"exec_nswaps" numeric,
	"exec_reads" numeric,
	"exec_reads_blks" numeric,
	"exec_writes" numeric,
	"exec_writes_blks" numeric,
	"exec_msgsnds" numeric,
	"exec_msgrcvs" numeric,
	"exec_nsignals" numeric,
	"exec_nvcsws" numeric,
	"exec_nivcsws" numeric
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vwPersons" (
	"id" integer,
	"namewcompany" varchar,
	"prefix" varchar,
	"firstname" varchar,
	"middlename" varchar,
	"lastname" varchar,
	"suffix" varchar,
	"firstlast" varchar,
	"companyid" integer,
	"companyname" varchar,
	"company" varchar,
	"department" varchar,
	"title" varchar,
	"preferredaddress" varchar,
	"preferredbillingaddress" varchar,
	"preferredshippingaddress" varchar,
	"addressid" integer,
	"addressline1" varchar,
	"addressline2" varchar,
	"addressline3" varchar,
	"addressline4" varchar,
	"city" varchar,
	"county" varchar,
	"state" varchar,
	"zipcode" varchar,
	"zipcode5numeric" integer,
	"country" varchar,
	"countrycodeid" integer,
	"preferredphone" varchar,
	"phoneid" integer,
	"phonecountrycode" varchar,
	"phoneareacode" varchar,
	"phone" varchar,
	"phoneextension" varchar,
	"faxid" integer,
	"faxcountrycode" varchar,
	"faxareacode" varchar,
	"faxphone" varchar,
	"cellphoneid" integer,
	"cellcountrycode" varchar,
	"cellareacode" varchar,
	"cellphone" varchar,
	"pagerphoneid" integer,
	"pagercountrycode" varchar,
	"pagerareacode" varchar,
	"pagerphone" varchar,
	"pagerphoneextension" varchar,
	"email" varchar,
	"email1" varchar,
	"email2" varchar,
	"email3" varchar,
	"billingaddressid" integer,
	"billingaddressline1" varchar,
	"billingaddressline2" varchar,
	"billingaddressline3" varchar,
	"billingaddressline4" varchar,
	"billingcity" varchar,
	"billingcounty" varchar,
	"billingstate" varchar,
	"billingzipcode" varchar,
	"billingcountrycodeid" integer,
	"billingcountry" varchar,
	"homeaddressid" integer,
	"homeaddressline1" varchar,
	"homeaddressline2" varchar,
	"homeaddressline3" varchar,
	"homeaddressline4" varchar,
	"homecity" varchar,
	"homecounty" varchar,
	"homestate" varchar,
	"homezipcode" varchar,
	"homecountry" varchar,
	"homephoneid" integer,
	"homecountrycodeid" integer,
	"homecountrycode" varchar,
	"homeareacode" varchar,
	"homephone" varchar,
	"poboxaddressid" integer,
	"pobox" varchar,
	"poboxline2" varchar,
	"poboxline3" varchar,
	"poboxline4" varchar,
	"poboxcity" varchar,
	"poboxcounty" varchar,
	"poboxstate" varchar,
	"poboxzipcode" varchar,
	"poboxcountrycodeid" integer,
	"poboxcountry" varchar,
	"socialsecurity" varchar,
	"organizationid" integer,
	"mainaccountmanager" integer,
	"mainaccountmanagername" varchar,
	"ranking" integer,
	"referredby" integer,
	"referraltype" varchar,
	"website" varchar,
	"birthday" timestamp,
	"supervisor" varchar,
	"assistantsname" varchar,
	"assistantsphoneid" integer,
	"assistantscountrycode" varchar,
	"assistantsareacode" varchar,
	"assistantsphone" varchar,
	"assistantsextension" varchar,
	"nickname" varchar,
	"gender" integer,
	"spousename" varchar,
	"kids" varchar,
	"importantdate1" timestamp,
	"importantdescription1" varchar,
	"importantdate2" timestamp,
	"importantdescription2" varchar,
	"importantdate3" timestamp,
	"importantdescription3" varchar,
	"atmosphere" varchar,
	"mailcode" varchar,
	"crrt" varchar,
	"uscongress" varchar,
	"statesenate" varchar,
	"statehouse" varchar,
	"countydistrict" varchar,
	"nextcontactdate" timestamp,
	"mailexclude" boolean,
	"faxexclude" boolean,
	"emailexclude" boolean,
	"direxclude" boolean,
	"prefcommmethodid" integer,
	"contactmanagerid" varchar,
	"verifystatus" varchar,
	"functionaltitle" varchar,
	"contactrank" varchar,
	"dirrank" integer,
	"primaryfunctionid" integer,
	"primaryfunction" varchar,
	"membertypeid" integer,
	"membertype" varchar,
	"joindate" timestamp,
	"duespaidthru" timestamp,
	"lastduespaymentdate" timestamp,
	"lastduesamount" numeric(19, 4),
	"terminationdate" timestamp,
	"status" integer,
	"companymembertypeid" integer,
	"comembertype" varchar,
	"companymembertype" varchar,
	"companyjoindate" timestamp,
	"companyduespaidthru" timestamp,
	"companylastduespaymentdate" timestamp,
	"companylastduesamount" numeric(19, 4),
	"companyterminationdate" timestamp,
	"oldid" varchar,
	"oldcompanyid" varchar,
	"glorderlevelid" integer,
	"glpaymentlevelid" integer,
	"creditstatusid" integer,
	"creditlimit" numeric(19, 4),
	"billingterms" varchar,
	"apvendorid" varchar,
	"preferredcurrencytypeid" integer,
	"directions" varchar,
	"Comments" varchar,
	"whocreated" varchar,
	"whoupdated" varchar,
	"datecreated" timestamp,
	"dateupdated" timestamp,
	"lastduesamountcurrencytypeid" integer,
	"creditlimitcurrencytypeid" integer,
	"companylastduesamountcurrencytypeid" integer,
	"macpa_aicpanumber" varchar,
	"macpa_aicpamember" varchar,
	"macpa_federaltaxid" varchar,
	"macpa_minoritygroup" varchar,
	"macpa_priorname" varchar,
	"macpa_region" varchar,
	"macpa_reinstatedate" timestamp,
	"macpa_badgecredentials" varchar,
	"macpa_terminationreasonid" integer,
	"macpa_terminationreason" varchar,
	"macpa_legacy_bc" varchar,
	"macpa_legacy_ty" varchar,
	"macpa_legacy_me" varchar,
	"macpa_gendername" varchar,
	"macpa_secondaryjoindate" date,
	"macpa_legacychapter" varchar,
	"macpa_speakerstatus" varchar,
	"macpa_speakernotes" varchar,
	"macpa_bio" varchar,
	"macpa_biolastupdated" timestamp,
	"macpa_memberstatus" varchar,
	"macpa_statustype" varchar,
	"cpastatecensus" varchar,
	"cpadistrictcode" varchar,
	"cpadistricttypeid" integer,
	"cpadistricttype" varchar,
	"cpapoliticalpartyid" integer,
	"cpapoliticalparty" varchar,
	"cpalegislatorid" varchar,
	"cpaisactivelegislator" integer,
	"macpa_legacyuscongress" varchar,
	"macpa_legacystatesenate" varchar,
	"macpa_legacystatehouse" varchar,
	"macpa_cpetotalaa" numeric(10, 2),
	"macpa_cpetotalet" numeric(10, 2),
	"macpa_cpetotalot" numeric(10, 2),
	"macpa_cpetotaldlaa" numeric(10, 2),
	"macpa_cpetotaldlet" numeric(10, 2),
	"macpa_cpetotaldlot" numeric(10, 2),
	"macpa_cpetotal" numeric(10, 2),
	"cpapersonalfaxid" integer,
	"cpapersonalfaxcountrycode" varchar,
	"cpapersonalfaxareacode" varchar,
	"cpapersonalfaxphone" varchar,
	"macpa_creditmemototal" numeric(19, 4),
	"macpa_nosuggestedpac" boolean,
	"macpa_pacagreementexemption" boolean,
	"macpa_paccoalition" boolean,
	"macpa_companytype" varchar,
	"macpa_badgename" varchar,
	"macpa_pacribbon" varchar,
	"macpa_reviewerpr" boolean,
	"macpa_technicalreviewerpr" boolean,
	"macpa_nopacdonations" boolean,
	"macpa_fullname" varchar,
	"macpa_preferredaddressid" varchar,
	"macpa_preferredaddressline1" varchar,
	"macpa_preferredaddressline2" varchar,
	"macpa_preferredaddressline3" varchar,
	"macpa_preferredaddressline4" varchar,
	"macpa_preferredcity" varchar,
	"macpa_preferredstate" varchar,
	"macpa_preferredzip" varchar,
	"macpa_preferredcounty" varchar,
	"macpa_preferredcountry" varchar,
	"macpa_joindate" timestamp,
	"ordertotal__fvc" numeric(19, 4),
	"balancedue__fvc" numeric(19, 4),
	"macpa_balancedue" varchar,
	"macpa_iscurrentlegislator" boolean,
	"macpa_legislatordistricttype" varchar,
	"macpa_legislatordistrict" varchar,
	"macpa_legislatorid" integer,
	"macpa_legislativeprefix" varchar,
	"macpa_legislativesuffix" varchar,
	"macpa_legprintflag" varchar,
	"macpa_noteligibleformembership" boolean,
	"photo" "bytea",
	"billingbadaddress" boolean,
	"homebadaddress" boolean,
	"poboxbadaddress" boolean,
	"businessbadaddress" boolean,
	"macpa_importsource" varchar,
	"macpa_currentushouse__c" varchar,
	"macpa_currentmisenate__c" varchar,
	"macpa_currentmihouse__c" varchar,
	"macpa_pastushouse__c" varchar,
	"macpa_pastmisenate__c" varchar,
	"macpa_pastmihouse__c" varchar,
	"kwpersonid" bigint,
	"legislatorreviewrequired" boolean,
	"externalaccountprofileurl" varchar,
	"ignoresocialnetworkcompanydifferences" boolean,
	"ignoresocialnetworktitledifferences" boolean,
	"isgroupadmin" boolean,
	"macpa_ismember" boolean,
	"micpa_mailballot" boolean,
	"micpa_duesmessage" varchar,
	"micpa_firmadmin" boolean,
	"micpa_excludefirmroster" boolean,
	"duesautoisactive__fvc" boolean,
	"cesscore" numeric(28, 0),
	"spacelinkhandle" varchar,
	"statusname" varchar,
	"formattedaddress" varchar,
	"formattedphone" varchar,
	"issystem" boolean,
	"micpa_importdate1" date,
	"micpa_importdate2" date,
	"micpa_formattedcellphone" varchar,
	"micpa_absorblmsid" varchar,
	"estoreid" integer,
	"vip_micpa" boolean,
	"scholarshipwinner" boolean,
	"micpa_peerreviewprofessional" boolean,
	"micpa_overridepac" numeric(19, 4),
	"originallicensedate_pb" timestamp
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vwPersonCPALicenses" (
	"id" integer,
	"personid" integer,
	"Sequence" integer,
	"licensetypeid" integer,
	"licensetype" varchar,
	"licenseno" varchar,
	"licensedate" timestamp,
	"licensestate" varchar,
	"licensestatusid" integer,
	"licensestatus" varchar,
	"expirationdate" timestamp,
	"micpa_larastatus" varchar,
	"micpa_lastrenewaldate" timestamp
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vwMeetingAttendees" (
	"id" integer,
	"registrant" varchar,
	"company" varchar,
	"travellingfrom" varchar,
	"arriving" timestamp,
	"departing" timestamp,
	"airline" varchar,
	"hotel" varchar,
	"orderid" integer,
	"meetingid" integer,
	"actualmeetingid" integer,
	"namewcompany" varchar
);

*/